### ISSUE TITLE
Error while sending a simple event.

### ISSUE THREAD

**Issue by smarigowda** [riemann/riemann-nodejs-client#38] opened 2021-05-03 11:33 UTC
![image](https://user-images.githubusercontent.com/1831259/116871174-c1bdef00-ac0b-11eb-8a32-55617740c41e.png)

![image](https://user-images.githubusercontent.com/1831259/116871241-e0bc8100-ac0b-11eb-850a-e46206845333.png)

**Comment by jamtur01** [comment] 2021-05-03 13:14
Duplicate of #35.

**Closed by jamtur01** 2021-05-03 13:14 UTC
